# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': '货币汇率管理', 'verbose_name_plural': '货币汇率管理'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '商品管理', 'verbose_name_plural': '商品管理'},
        ),
        migrations.AlterModelOptions(
            name='goodscategory',
            options={'verbose_name': '商品分类管理', 'verbose_name_plural': '商品分类管理'},
        ),
        migrations.AlterModelOptions(
            name='goodslib',
            options={'verbose_name': '商品库管理', 'verbose_name_plural': '商品库管理'},
        ),
        migrations.AlterModelOptions(
            name='goodssecondcategory',
            options={'verbose_name': '商品二级分类管理', 'verbose_name_plural': '商品二级分类管理'},
        ),
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '商品规格管理', 'verbose_name_plural': '商品规格管理'},
        ),
        migrations.AddField(
            model_name='goods',
            name='kaola_price',
            field=models.IntegerField(default=0, verbose_name='考拉价'),
        ),
        migrations.AddField(
            model_name='goods',
            name='taobao_price',
            field=models.IntegerField(default=0, verbose_name='淘宝价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='currency_name',
            field=models.CharField(default='人民币', max_length=16, verbose_name='货币单位'),
        ),
    ]
